### PR TITLE
fix: use domain as parameter

### LINKED ISSUE #59: [BUG] Use `{{domain}}` instead go `.self` in components
### Description
Fix example and test components to use `{{domain}}` instead go `.self` to be aligned with the updated mighty structure.

### Impact
None. Components inside this package is only used internally.

### Related Issues
Update needed for #17.

### PR DESCRIPTION
**Pull request by akselthomsen**
# Pull request

## Summary
Updated all internal example and tests templates to use `{{domain}}` instead of `.self`.

This PR is not optimal in the sense that the testing framework will be updated in #48, which means there are some quick fixes here that will be replaced very soon.

I considered implementing the `{{domain}}` in #48 as well, but thought it was better to keep it separate, even if this update is necessary for the unit test development to continue.

## Changes Made
- Updated all example components in `inst/components`. Implemented `{{domain}}` as param.
- Likewise for unit tests components in `tests/testthat/_components`
- Updated examples to also use domain when rendering the components.
- Removed `input` argument from `msr_test()`. Using a temporary `value = "domain"` right now to test it. Will be completely replaced in the above mentioned PR.

## Testing
- Updated tests to also supply `domain` as rendering parameter
- Skipping unit testing of the example components in `inst/components` due to the testing framework being updated as well. Once updated, these should pass. 
- Added helper `expect_ady()` function in `test-component.R` to reduce copy-paste code.

## Checklist
- [x] Code changes have been tested
- [x] Documentation has been updated, if applicable
- [x] All automated tests pass
- [x] Coding style and naming conventions have been followed
- [x] The PR is ready for review and merge

### CODE REVIEW

**Review by matthew-phelps — COMMENTED** [review]
See my one comment, otherwise GTG

File: R/mighty_component_rendered.R [hunk 1]
```diff
@@ -50,12 +50,11 @@ mighty_component_rendered <- R6::R6Class(
     },
     #' @description
     #' Test component against expected output.
-    #' @param input The input to use as `.self` for the code chunk
     #' @param expected The expected output in `.self` after evaluation
```
Comment (matthew-phelps) [inline R/mighty_component_rendered.R]: "The expected output in the domain after evaluation"?

Comment (akselthomsen) [reply R/mighty_component_rendered.R]: Good catch! I have updated to reflect the setup better.

**Comment by qAnblgrIOxo3DtVcosLy3Ci9mtI6vndY2y4OejS** [comment]
# Github pages
Review the pkgdown webpage for the PR [here](https://NN-OpenSource.github.io/mighty.component/dev/60)

**Review by matthew-phelps — APPROVED** [review]

**Comment by qAnblgrIOxo3DtVcosLy3Ci9mtI6vndY2y4OejS** [comment]
# Code coverage
|Name                          | Coverage (%)|
|:-----------------------------|------------:|
|mighty.component              |          100|
|R/component.R                 |          100|
|R/custom_r.R                  |          100|
|R/mighty_component_rendered.R |          100|
|R/mighty_component.R          |          100|
|R/standard.R                  |          100|
|R/utils-validation.R          |          100|
